<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ScoreBoardSelfActivitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('scoreboard_selfactivity')->insert([
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'self_activity_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'self_activity_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'self_activity_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'self_activity_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'self_activity_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'self_activity_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'self_activity_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'self_activity_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'self_activity_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'self_activity_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'self_activity_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'activity_content' => 'none',
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'self_activity_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
