<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ScoreBoardSchoolsActivitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('scoreboard_schoolsactivity')->insert([
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'schools_activity_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'schools_activity_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'schools_activity_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'schools_activity_id' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'schools_activity_id' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'schools_activity_id' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 1,
                'schools_activity_id' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'schools_activity_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'schools_activity_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'schools_activity_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'schools_activity_id' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'schools_activity_id' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'schools_activity_id' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 2,
                'schools_activity_id' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'schools_activity_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'schools_activity_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'schools_activity_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'schools_activity_id' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'schools_activity_id' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'schools_activity_id' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 3,
                'schools_activity_id' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'schools_activity_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'schools_activity_id' => 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'schools_activity_id' => 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'schools_activity_id' => 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'schools_activity_id' => 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'schools_activity_id' => 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'average_score' => 0,
                'confirmingStudent' => 0,
                'confirmingClass' => 0,
                'confirmingFaculty' => 0,
                'confirmingSchool' => 0,
                'score_board_id' => 4,
                'schools_activity_id' => 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            
        ]);
    }
}
